"use strict";(self.webpackChunkdumi_monorepo_template=self.webpackChunkdumi_monorepo_template||[]).push([[56],{21406:function(d,n,e){e.r(n),e.d(n,{demos:function(){return E}});var r=e(90228),o=e.n(r),p=e(87999),s=e.n(p),_=e(75271),E={"packages-component-src-hello-world-demo-0":{component:_.memo(_.lazy(s()(o()().mark(function a(){var i,u,m,l;return o()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,Promise.resolve().then(e.t.bind(e,75271,19));case 2:return i=t.sent,u=i.default,t.next=6,Promise.resolve().then(e.bind(e,541));case 6:return m=t.sent,l=m.HelloWorld,t.abrupt("return",{default:function(){return u.createElement("h1",null,u.createElement(l,null))}});case 9:case"end":return t.stop()}},a)})))),asset:{type:"BLOCK",id:"packages-component-src-hello-world-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import React from 'react';
import { HelloWorld } from '@nm/component';

export default () => (
  <h1>
    <HelloWorld />
  </h1>
);`},react:{type:"NPM",value:"18.3.1"},"@nm/component":{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{react:e(75271),"@nm/component":e(541)},renderOpts:{compile:function(){var a=s()(o()().mark(function u(){var m,l=arguments;return o()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,e.e(455).then(e.bind(e,90455));case 2:return t.abrupt("return",(m=t.sent).default.apply(m,l));case 3:case"end":return t.stop()}},u)}));function i(){return a.apply(this,arguments)}return i}()}}}},96416:function(d,n,e){e.r(n),e.d(n,{demos:function(){return o}});var r=e(75271),o={}},53738:function(d,n,e){e.r(n),e.d(n,{demos:function(){return E}});var r=e(90228),o=e.n(r),p=e(87999),s=e.n(p),_=e(75271),E={"packages-ui-src-legend-demo-0":{component:_.memo(_.lazy(s()(o()().mark(function a(){var i,u,m,l;return o()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,Promise.resolve().then(e.t.bind(e,75271,19));case 2:return i=t.sent,u=i.default,t.next=6,Promise.resolve().then(e.bind(e,92954));case 6:return m=t.sent,l=m.Legend,t.abrupt("return",{default:function(){return u.createElement("h1",null,u.createElement(l,null))}});case 9:case"end":return t.stop()}},a)})))),asset:{type:"BLOCK",id:"packages-ui-src-legend-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import React from 'react';
import { Legend } from '@nm/ui';

export default () => (
  <h1>
    <Legend />
  </h1>
);`},react:{type:"NPM",value:"18.3.1"},"@nm/ui":{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{react:e(75271),"@nm/ui":e(92954)},renderOpts:{compile:function(){var a=s()(o()().mark(function u(){var m,l=arguments;return o()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,e.e(455).then(e.bind(e,90455));case 2:return t.abrupt("return",(m=t.sent).default.apply(m,l));case 3:case"end":return t.stop()}},u)}));function i(){return a.apply(this,arguments)}return i}()}}}},2770:function(d,n,e){e.r(n),e.d(n,{demos:function(){return o}});var r=e(75271),o={}},55823:function(d,n,e){e.r(n),e.d(n,{demos:function(){return o}});var r=e(75271),o={}},81041:function(d,n,e){e.r(n),e.d(n,{demos:function(){return i}});var r=e(90228),o=e.n(r),p=e(48305),s=e.n(p),_=e(87999),E=e.n(_),a=e(75271),i={"packages-util-src-sum-demo-0":{component:a.memo(a.lazy(E()(o()().mark(function u(){var m,l,c,t,h,v,P;return o()().wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return f.next=2,Promise.resolve().then(e.t.bind(e,75271,19));case 2:return m=f.sent,l=m.default,c=m.useState,f.next=7,Promise.resolve().then(e.bind(e,336));case 7:return t=f.sent,h=t.sum,f.next=11,Promise.resolve().then(e.bind(e,44016));case 11:return v=f.sent,P=v.Button,f.abrupt("return",{default:function(){var y=c(0),M=s()(y,2),O=M[0],D=M[1];return l.createElement("div",null,l.createElement("p",null,O),l.createElement(P,{onClick:function(){return D(h(O,1))}},"\u52A0 1"))}});case 14:case"end":return f.stop()}},u)})))),asset:{type:"BLOCK",id:"packages-util-src-sum-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import React, { useState } from 'react';
import { sum } from '@nm/util';
import { Button } from 'antd';

export default () => {
  const [val, setVal] = useState(0);
  return (
    <div>
      <p>{val}</p>
      <Button onClick={() => setVal(sum(val, 1))}>\u52A0 1</Button>
    </div>
  );
};`},react:{type:"NPM",value:"18.3.1"},"@nm/util":{type:"NPM",value:"1.0.0"},antd:{type:"NPM",value:"5.18.1"}},entry:"index.jsx"},context:{react:e(75271),"@nm/util":e(336),antd:e(44016)},renderOpts:{compile:function(){var u=E()(o()().mark(function l(){var c,t=arguments;return o()().wrap(function(v){for(;;)switch(v.prev=v.next){case 0:return v.next=2,e.e(455).then(e.bind(e,90455));case 2:return v.abrupt("return",(c=v.sent).default.apply(c,t));case 3:case"end":return v.stop()}},l)}));function m(){return u.apply(this,arguments)}return m}()}}}},541:function(d,n,e){e.r(n),e.d(n,{HelloWorld:function(){return s}});var r=e(75271),o=e(52676),p=function(){return(0,o.jsx)("div",{children:"HelloWorld"})},s=p},92954:function(d,n,e){e.r(n),e.d(n,{Legend:function(){return E}});var r=e(541),o=e(97590),p=e(75271),s=e(52676),_=function(){return(0,s.jsxs)("div",{children:[(0,s.jsx)(r.HelloWorld,{}),(0,s.jsx)(o.ZP,{children:"Antd Button"})]})},E=_},336:function(d,n,e){e.r(n),e.d(n,{sum:function(){return r}});function r(o,p){return o+p}},91206:function(d,n,e){e.r(n),e.d(n,{texts:function(){return r}});const r=[]},87022:function(d,n,e){e.r(n),e.d(n,{texts:function(){return r}});const r=[{value:"@nm/component",paraId:0,tocIndex:0}]},16212:function(d,n,e){e.r(n),e.d(n,{texts:function(){return r}});const r=[]},88256:function(d,n,e){e.r(n),e.d(n,{texts:function(){return r}});const r=[{value:"@nm/ui",paraId:0,tocIndex:0}]},78961:function(d,n,e){e.r(n),e.d(n,{texts:function(){return r}});const r=[{value:"@nm/util",paraId:0,tocIndex:0}]},54553:function(d,n,e){e.r(n),e.d(n,{texts:function(){return r}});const r=[]}}]);
